// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalonManagement.API.Data;

namespace SalonManagement.API.Data.Migrations
{
    [DbContext(typeof(ContextoDeDados))]
    partial class ContextoDeDadosModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("SalonManagement.API.Models.Servico", b =>
                {
                    b.Property<int>("ServicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cliente")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataServico")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoServico")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProdutoUtilizadoServico")
                        .HasColumnType("TEXT");

                    b.Property<double>("ValorServico")
                        .HasColumnType("REAL");

                    b.HasKey("ServicoId");

                    b.ToTable("Servicos");
                });
#pragma warning restore 612, 618
        }
    }
}
